Repository goharbor/harbor-cluster-operator, pull requests merged in 2020-08, with the labels that each got.

#132 fix(registry): add new item
  Dockerfile
  api/v1/harborcluster_types.go
  config/manager/kustomization.yaml
  controllers/database/generate.go
  controllers/harbor/provision.go
  go.mod
  go.sum
Labels: bug

#138 feat(cache) support provison inCluster single redis
  Dockerfile
  Makefile
  config/manager/manager.yaml
  controllers/cache/client.go
  controllers/cache/constants.go
  controllers/cache/generate.go
  controllers/cache/provision.go
  controllers/cache/readiness.go
  controllers/cache/utils.go
Labels: area/dep-redis

#152 feat(api): print more info when using `kubectl get harborcluster`
  api/v1/harborcluster_types.go
Labels: area/CRD

#155 doc(installation): add guide to deploy harbor on Kind cluster
  docs/installation_local.md
Labels: area/deployment, documentation

#171 fix(harbor): fix NPE in the operator controller
  controllers/harbor/provision.go
Labels: bug

#177 feat(operator):add kustomization templates
  manifests/README.md
  manifests/all-in-one.yaml
  manifests/core-operator/all-core-operator-resources.yaml
  manifests/kustomization.yaml
  manifests/namespaces/namespaces.yaml
  manifests/patches/postgres/cluster-rb-patch.yaml
  manifests/patches/postgres/namespace-patch.yaml
  manifests/patches/postgres/namespace-replace-patch.yaml
  manifests/patches/redis/cluster-rb-patch.yaml
  manifests/patches/redis/namespace-patch.yaml
Labels: area/deployment, area/kustomization, improvement

#181 doc(installation):re-organize installation guides
  README.md
  docs/README.md
  docs/architecture.md
  docs/cr_HarborCluster_spec.md
  docs/installation.md
  docs/installation_external.md
  docs/sample_deploy_guide.md
Labels: area/deployment, documentation
