Repository goharbor/harbor-cluster-operator, pull requests merged in 2020-09, with the labels that each got.

#179 feat(image):add support version v1.10.x(>2)
  controllers/harbor/harbor.go
  controllers/harborcluster_controller.go
  controllers/image/harbor_v1.10.x.go
  controllers/image/image.go
  controllers/service.go
  go.mod
  go.sum
Labels: area/deployment, improvement

#186 fix(golint): fix golint error
  controllers/cache/generate.go
  controllers/cache/labels.go
  controllers/cache/utils.go
  controllers/database/utils.go
  controllers/image/image.go
  controllers/storage/minio.go
  controllers/storage/provision.go
Labels: bug

#205 fix(reconcile): update ctrl.Result to requeue the key for updating st…
  controllers/harborcluster_controller.go
Labels: area/controller, bug

#206 fix(manifests): update operator deploy manifests
  manifests/all-in-one.yaml
  manifests/core-operator/all-core-operator-resources.yaml
  manifests/kustomization.yaml
Labels: area/deployment, release/0.5

#212 doc(installation):add and update installation guides
  docs/sample_deploy_guide.md
  manifests/kustomization.yaml
  samples/incluster/README.md
  samples/incluster/inCluster.yaml
Labels: release/0.5

#223 fix ing svc name
  controllers/storage/provision.go
Labels: area/dep-minio, bug

#225 update rbac ingresses
  controllers/harborcluster_controller.go
Labels: bug

#224 fix minio secret data
  controllers/storage/provision.go
Labels: area/dep-minio, bug
